import type { AtlasGraph } from '../graph.js';
import { flowDiagram, topologyDiagram } from './mermaid.js';

/** Render SYSTEM.md: the file an agent reads before touching the system. */
export function renderSystemMd(graph: AtlasGraph): string {
  const { atlas } = graph;
  const compute = atlas.nodes.filter((n) => ['service', 'function', 'gateway', 'frontend'].includes(n.kind));
  const data = atlas.nodes.filter((n) => ['database', 'cache', 'storage', 'search'].includes(n.kind));
  const messaging = atlas.nodes.filter((n) => ['queue', 'topic', 'stream'].includes(n.kind));
  const external = atlas.nodes.filter((n) => n.kind === 'external');
  const cell = (s?: string) => (s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const list = (ids: string[]) => (ids.length ? ids.map((i) => `\`${i}\``).join(', ') : '—');

  const out: string[] = [
    '<!-- Generated by AgentAtlas. Do not edit by hand: change agentatlas.yaml or the code, then run `agentatlas scan`. -->',
    `# System map: ${atlas.system.name}`,
    '',
    ...(atlas.system.description ? [atlas.system.description, ''] : []),
    '## For AI agents',
    '',
    '- Read this file before changing code that crosses a service boundary.',
    '- Before changing a service, check **Used by** for everything that may break.',
    '- Edges point from the dependent to the dependency. `publishes`/`consumes` mark async messaging; contracts on those edges are just as binding as HTTP APIs.',
    '- The full graph is in `.agentatlas/atlas.yaml`. If the `agentatlas` MCP server is available, prefer its tools (`get_service`, `impact_of_change`, `trace_flow`).',
    '',
    '## Topology',
    '',
    '```mermaid',
    topologyDiagram(graph),
    '```',
    '',
  ];

  if (compute.length) {
    out.push('## Services', '', '| Service | Kind | Tech | Depends on | Used by |', '|---|---|---|---|---|');
    for (const n of compute) {
      out.push(`| [\`${n.id}\`](#${n.id}) | ${n.kind} | ${cell(n.tech?.join(', '))} | ${list(graph.outgoing(n.id).map((e) => e.to))} | ${list(graph.incoming(n.id).map((e) => e.from))} |`);
    }
    out.push('');
  }
  if (data.length || messaging.length) {
    out.push('## Data and messaging', '', '| Resource | Kind | Tech | Writers / publishers | Readers / consumers |', '|---|---|---|---|---|');
    for (const n of [...data, ...messaging]) {
      const inc = graph.incoming(n.id);
      const writers = inc.filter((e) => e.kind !== 'consumes').map((e) => e.from);
      const readers = inc.filter((e) => e.kind === 'consumes').map((e) => e.from);
      out.push(`| \`${n.id}\` | ${n.kind} | ${cell(n.tech?.join(', '))} | ${list(writers)} | ${n.kind === 'topic' || n.kind === 'queue' || n.kind === 'stream' ? list(readers) : '—'} |`);
    }
    out.push('');
  }
  if (external.length) {
    out.push('## External systems', '', '| System | Description | Used by |', '|---|---|---|');
    for (const n of external) out.push(`| \`${n.id}\` | ${cell(n.description)} | ${list(graph.incoming(n.id).map((e) => e.from))} |`);
    out.push('');
  }

  out.push('## Service details', '');
  for (const n of compute) {
    out.push(`### ${n.id}`, '');
    if (n.description) out.push(n.description, '');
    const facts = [
      n.owner && `**Owner:** ${n.owner}`,
      n.hosting && `**Hosting:** ${n.hosting}`,
      n.repoPath && `**Code:** \`${n.repoPath}\``,
      `**Found by:** ${n.sources.join(', ')}`,
    ].filter(Boolean);
    out.push(facts.join(' · '), '');
    const deps = graph.outgoing(n.id);
    if (deps.length) {
      out.push('**Depends on**', '');
      deps.forEach((e) => out.push(`- ${e.kind} \`${e.to}\`${e.protocol ? ` (${e.protocol})` : ''}${e.observed ? ` — seen ${e.observed}x in traces` : ''}`));
      out.push('');
    }
    const users = graph.incoming(n.id);
    if (users.length) {
      out.push('**Used by**', '');
      users.forEach((e) => out.push(`- \`${e.from}\` ${e.kind}`));
      out.push('');
    }
    if (n.endpoints?.length) {
      out.push('**Endpoints**', '');
      n.endpoints.forEach((e) => out.push(`- \`${e.method} ${e.path}\`${e.summary ? ` — ${e.summary}` : ''}`));
      out.push('');
    }
  }

  if (atlas.flows.length) {
    out.push('## Flows', '');
    for (const f of atlas.flows) {
      out.push(`### ${f.name}`, '', ...(f.description ? [f.description, ''] : []), '```mermaid', flowDiagram(f, atlas), '```', '');
    }
  }
  return `${out.join('\n').trimEnd()}\n`;
}
