import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parse, stringify } from 'yaml';
import { ATLAS_FILE, OUTPUT_DIR, SYSTEM_FILE } from './config.js';
import { AtlasGraph } from './graph.js';
import type { Atlas } from './model.js';
import { renderSystemMd } from './render/system-md.js';
import { readText } from './util.js';

const HEADER = '# Generated by AgentAtlas (https://github.com/senthil-sekar/agent-atlas).\n# Edit agentatlas.yaml instead, then run `agentatlas scan`.\n';

export const atlasPath = (dir: string) => join(dir, OUTPUT_DIR, ATLAS_FILE);
export const systemPath = (dir: string) => join(dir, SYSTEM_FILE);

export function serializeAtlas(atlas: Atlas): string {
  return HEADER + stringify(atlas, { lineWidth: 0 });
}

export function readAtlas(dir: string): Atlas | undefined {
  const text = readText(atlasPath(dir));
  if (text === undefined) return undefined;
  const doc = parse(text) as Atlas;
  if (!doc || doc.version !== 1 || !Array.isArray(doc.nodes)) throw new Error(`${atlasPath(dir)} is not a valid atlas file`);
  doc.edges ??= [];
  doc.flows ??= [];
  return doc;
}

export function writeOutputs(dir: string, atlas: Atlas): string[] {
  mkdirSync(join(dir, OUTPUT_DIR), { recursive: true });
  writeFileSync(atlasPath(dir), serializeAtlas(atlas));
  writeFileSync(systemPath(dir), renderSystemMd(new AtlasGraph(atlas)));
  return [atlasPath(dir), systemPath(dir)];
}
